name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *" #run every at 00:00:00s UTC / 08.00 GMT +7 / 09.00 GMT +8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pandas
          pip install requests
      - name: Execute Script
        run: |
          python script/harian.py
          echo "harian.py Done"

          python script/jenis_kelamin.py
          echo "jenis_kelamin.py Done"

          python script/pemeriksaan-vaksinasi.py
          echo "pemeriksaan-vaksinasi.py Done"

          python script/provinsi.py
          echo "provinsi.py Done"

          python script/usia.py
          echo "usia.py Done"

          python script/rumah_sakit.py
          echo "rumah_sakit.py Done"

          python script/lab.py
          echo "lab.py Done"

      - name: Commit File
        run: |
          git config --local user.email "81743021+mzakiyuddin@users.noreply.github.com"
          git config --local user.name "mzakiyuddin"
          git add .
          now=$(date)
          git commit -m "Auto Commit $now"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
